### ISSUE TITLE
How to enable BLE for Cytone?

### ISSUE THREAD

**Issue by itisnas** [PushTheWorld/OpenBCI_NodeJS_Cyton_BLE#2]
I've managed to get my hands on BLE and everything is ready. One thing remains is that the Cyton is not publicly visible, even though its switched to BLE mode instead of PC.

Is there any modification that we must do?

In the post, we are told that the RFDuino must import the RFDuino.h. How do we do this in order to allow BLE?
<img width="815" alt="capture" src="https://user-images.githubusercontent.com/16179773/35408607-b6d6c514-0207-11e8-9858-94a368be8721.PNG">

**Comment by andrewjaykeller** [comment]
You need to hardware upload the [ble code](https://github.com/PushTheWorld/OpenBCI_RFDuino_BLE) on the cyton’s RFDuino AFTER over the air uploading the BoardWithBLE.ino to the Cyton’s Pic32

**Comment by itisnas** [comment]
Sorry to be a pain, I have absolutely no idea how to do this (extremely new to arduino programming)?

So do you want me to upload the whole [`directory`](https://github.com/PushTheWorld/OpenBCI_RFDuino_BLE)? If so then specifically where? or what chunk of code must I copy?

And could you please clarify "over the air uploading the BoardWithBLE.ino to the Cyton’s Pic32"?

Thanks a bunch!

@aj-ptw

**Comment by itisnas** [comment]
Could you perhaps provide READme, this way you won't have to repeat the same instruction to those who might be looking for the same content?

**Comment by andrewjaykeller** [comment]
@NaseebullahSafi 

Thank so much for your interest in the project! I have just [added a section in readme](https://github.com/PushTheWorld/OpenBCI_NodeJS_Cyton_BLE#firmware) that i hope provides a little more clarity. Helping you achieve your goals is my number one goal so please do not stress about annoying me, I love when people ask lots of questions, because there are even more people not asking these questions. 

On another note, and please understand, I had to edit your comment above, (pain in the ...) to align with the [code of conduct](https://github.com/PushTheWorld/OpenBCI_NodeJS_Cyton_BLE/blob/master/CODE_OF_CONDUCT.md). There are people of all ages and creeds combing through these pages and we want to create a welcoming and profanity free atmosphere! I'm really excited to have you as a part of the community and I'm ready for the opportunity to help your professional development!

**Comment by itisnas** [comment]
Apologies, you had every right to do so what you wished. I shall bear that in mind. Thanks a ton!

**Comment by andrewjaykeller** [comment]
Absolutely no problem! I didn't answer your questions 100% so please let me know if you have any troubles!

**Comment by itisnas** [comment]
@aj-ptw I'm currently following every step at the moment. Was wondering, I bought the cyton board last week or so, and in the tutorial, it says "If you have blue buttons on your board you do not need the 0.1uF capacitor because it is already on the board.".

Where are these buttons usually located on the board? I think I have the latest cyton board.

Thanks

**Comment by andrewjaykeller** [comment]
I would assume your board already has it and try with out the capacitor.

Thanks,

AJ Keller
--------------------------------------------

Push The World LLC <http://www.pushtheworldllc.com/>
Unleash The Power of Thought

Warning: The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and destroy this material.

**Comment by itisnas** [comment]
I see, ok, so when I press the pins to cyton board, what do I do then? In the tutorial, it says:
"press them tightly against the sides of the holes to make a strong connection. Now, you can upload Device code to the RFduino on the OpenBCI 8-bit Board!"

But which which device code? @aj-ptw

**Comment by andrewjaykeller** [comment]
You have a Cyton board, not an 8-bit board. 

So your instructions are:

> On the Cyton Board the pins you need to connect to are accessed from the BOTTOM of the board. Connect the jumper wires to the center of the pads as shown and press tightly while uploading to the Device. Helpful tips: Use a 4pin female header to keep the wires in place Don’t move your hand at all Place the board on a table or hard surface Keep the pins straight up and centered on the pads. (perpendicular to the surface of the pads)

Your question:

> But which which device code?

Upload [OpenBCI_RFDuino_BLE](https://github.com/PushTheWorld/OpenBCI_RFDuino_BLE/blob/neba-ble/examples/DefaultRadio/DefaultRadio.ino)

This should have be answered by the [readme section](https://github.com/PushTheWorld/OpenBCI_NodeJS_Cyton_BLE#firmware)

> Upload DefaultRadio.ino to the Cyton's RFDuino through hardwire following this tutorial where you use the DefaultRadio.ino from OpenBCI_RFDuino_BLE. If you don't have an FTDI programmer and need to use the Dongle that shipped with your Cyton, then be sure to follow the part in the tutorial about uploading the pass through code to the Dongle.

Do you have any suggestions on how I can improve the README? I would love it if you could edit the readme and suggest a change through a pull request, or I'm happy to update as well!

**Comment by itisnas** [comment]
Yes thank you, as soon as I get this working, I'll upload the readme with pictures to clarify much confusion. Thanks.

**Comment by andrewjaykeller** [comment]
@NaseebullahSafi AWESOME!! Thank you so much!!!!!

**Comment by andrewjaykeller** [comment]
Keep the questions coming! Thanks so much for your help

**Comment by itisnas** [comment]
@aj-ptw Thank you. So I'm trying to upload RadioPassThrough32bit in [Upload Pass Thru Radio Firmware Version 2.x.x (Fall 2016)](http://docs.openbci.com/Hardware/06-Cyton_Radios_Programming_Tutorial#cyton-radios-programming-tutorial-using-radio-firmware-version-2xx-fall-2016)

<img width="1071" alt="capture" src="https://user-images.githubusercontent.com/16179773/35460907-846df224-02dd-11e8-8697-0f98205b205b.PNG">

And I get the following error. Could you please explain how to fix that?

**Comment by andrewjaykeller** [comment]
Please refer to these instructions to [setup your system for uploading](http://docs.openbci.com/Hardware/06-Cyton_Radios_Programming_Tutorial#cyton-radios-programming-tutorial-setting-up-your-system-to-program-openbci-radios).

You _must_ use 1.5.8 Beta

**Comment by itisnas** [comment]
@aj-ptw I manage to make it work. I will definitely update the README. Thanks for all the help and patience! 👍

**Comment by andrewjaykeller** [comment]
@NaseebullahSafi you just made my day!

**Comment by itisnas** [comment]
@aj-ptw Just One question, where do we specify which channel would we want to receive? In the GUI I had only cared about channel 4.

**Comment by andrewjaykeller** [comment]
You automatically get channel 1 and 2. Can you adapt to using just those?

**Comment by itisnas** [comment]
@aj-ptw ah right, ok thanks. Yh should be able to adapt to those 2. I'm gonna close this issue as it has been resolved.
