### ISSUE TITLE
What should happen if there's no service found for Cyton?

### ISSUE THREAD

**Issue by itisnas** [PushTheWorld/OpenBCI_NodeJS_Cyton_BLE#4]
Currently, when I call the connect method, it throws an error that services are null. Which is true because When I printed, this was shown:
<img width="884" alt="capture" src="https://user-images.githubusercontent.com/16179773/35580787-f4c34fea-05e1-11e8-8122-4dd828ebc458.PNG">

Here's what I have:

```js
    Cyton.once(constants.OBCIEmitterRFduino, (peripheral) => {

      Cyton.searchStop().then(() => {
        console.log("Hello:=> ", peripheral);
        console.log(`search stopped`);
        //console.log(peripheral.services);
        Cyton.connect(peripheral).catch(e => console.log(e));
      }).catch(e => console.log(e));
    });

    Cyton.once(constants.OBCIEmitterBlePoweredUp, () => {
      Cyton.searchStart().catch(e => console.log(e))
    });


    if (Cyton.isNobleReady()) {
      console.log(`noble is ready so starting scan`);
      Cyton.removeListener(constants.OBCIEmitterBlePoweredUp, () => {
        Cyton.searchStart().catch(e => console.log(e));
      });
    } else {
      console.log(`noble is NOT ready so waiting starting scan`);
    }

```

Now the question is, why is the service null, and what should we do when it is null?

Update
=

The weird thing is, when I run it now, although the *[`services`]* exist, but the error still shows:

<img width="1058" alt="capture" src="https://user-images.githubusercontent.com/16179773/35581062-a51d6876-05e2-11e8-8e5b-5b1166c76b0e.PNG">

And If I backtrack the error, it falls here:

<img width="769" alt="capture" src="https://user-images.githubusercontent.com/16179773/35581180-ee82d79e-05e2-11e8-9d00-95115e4b4a0d.PNG">

**Comment by andrewjaykeller** [comment]
what are the UUIDs for the services?

**Comment by itisnas** [comment]
These are the UUIDs
@aj-ptw 
<img width="927" alt="capture" src="https://user-images.githubusercontent.com/16179773/35582939-3a630666-05e8-11e8-9969-2d1c91c3cb9d.PNG">


Update
=
@aj-ptw I've did some debugging, and this is where it seems to break Btw, the 
**[`k.RFduinoUuidService`] = 2220**:

<img width="700" alt="capture" src="https://user-images.githubusercontent.com/16179773/35583341-87f7cfbe-05e9-11e8-845e-e0b7dfcf5682.PNG">

And here's the console for the line 789:
<img width="1064" alt="capture" src="https://user-images.githubusercontent.com/16179773/35583363-a04ad084-05e9-11e8-8c98-c3f2ce4bc006.PNG">

**Comment by itisnas** [comment]
@aj-ptw I'm thinking, why is my Cyton returning such huge UUID, whereas the UUID in the constant.js it is hardcoded.  Do I need to do some configuration on the Arduino side?

<img width="263" alt="capture" src="https://user-images.githubusercontent.com/16179773/35587138-c924eaca-05f4-11e8-8646-bb6bb96676fb.PNG">

**Comment by andrewjaykeller** [comment]
Can you interrogate the RFDuino with a BLE application like Light Blue? Check out what services and characteristics the RFDuino is outputting.

**Comment by NaseebullahSafi** [comment]
I'm not sure how to integrate it to Light blue. Is this done on the arduino side? @aj-ptw

**Comment by NaseebullahSafi** [comment]
Sorry I read your message wrong. Let me check

**Comment by itisnas** [comment]
@aj-ptw Ok so this is what I got from the application so far:
<img src="https://user-images.githubusercontent.com/16179773/35588889-ef29d9a6-05f9-11e8-96bf-687a4ef74c7c.jpg" height="600">

<img src="https://user-images.githubusercontent.com/16179773/35588890-ef4769e4-05f9-11e8-889b-6dbd467e9acc.jpg" height="600">

<img src="https://user-images.githubusercontent.com/16179773/35590160-de3f46ae-05fd-11e8-9246-28d91e3f78fa.jpg" height="600">

**Comment by itisnas** [comment]
@aj-ptw 

They seem to give out the same details as debugged in chrome @aj-ptw 

Update
=

Ok, I've found out the problem, but I don't know how to fix it. In other words, I don't know if this should be done from your side or my side.

When my device scans for devices like the RFduino, the services UUID format is different than that of the one set in constant.js. For example:

<img width="872" alt="capture" src="https://user-images.githubusercontent.com/16179773/35595217-cba24a40-060d-11e8-8dba-781514edddb3.PNG">


The uuid that I get is "00002220 00001000800000805f9b34fb" but in constant.js its set to:
```js
RFduinoUuidService : "2220"
```

I tried to change the value of the uuid inside the 
```js
CytonBLE.prototype._nobleConnect = function (peripheral) {...}
```

But this throws
>noble warning: unknown peripheral "CF:92:02:BC:0D:CE", 2220 characteristics discover

It would be really appreciated if you could help me figure this out. Currently, this problem only appears if I call the connect method.

**Comment by NaseebullahSafi** [comment]
Ok I think I found the solution. As you can see my UUIDs are long, and so if I can get the last 4 digits of the first chunk, then it will match the UUID in the contants.js. Is there a way of changing the UUIDs? @aj-ptw

**Comment by andrewjaykeller** [comment]
Hmm I wonder why your service IDs and characteristics are so long. You cannot change the uuid's. I went as far to confirm with another [driver i found written in Swift](https://github.com/Kukiwon/rfduino-swift/blob/master/Pod/Classes/RFDuinoBTManager.swift#L24) 

Keep in mind you are searching for an RFDuino, not a Cyton.

**Comment by andrewjaykeller** [comment]
Did you try running [examples/cytonBLEServer/cytonBLEServer.js](https://github.com/PushTheWorld/OpenBCI_NodeJS_Cyton_BLE/blob/master/examples/cytonBLEServer/cytonBLEServer.js) example?

**Comment by andrewjaykeller** [comment]
The correct characteristic to use is the one in this photo

![Photo from your previous post](https://user-images.githubusercontent.com/16179773/35588890-ef4769e4-05f9-11e8-889b-6dbd467e9acc.jpg)

**Comment by itisnas** [comment]
@aj-ptw Thank you for your work, really appreciated. 

Since I get the same details as mentioned in the photo you attached, then what could be the problem? Quite confused now

**Comment by andrewjaykeller** [comment]
Did you change the firmware on the RFDuino to Default radio?

**Comment by itisnas** [comment]
I believe so yes @aj-ptw Do you want me to redo the steps that you mentioned? Just to make sure, there could be absolutely no problem with the Cyton board that came as product right? (of course. There isn't, It's OpenBCI after all 💯 ).

I'm betting I've done something wrong in the firmware setup. I'm gonna make my way to university today and will redo the step. Will update you
 @aj-ptw

**Comment by andrewjaykeller** [comment]
@NaseebullahSafi we must figure out why your device is not advertising the correct UUIDs.

> I tried to change the value of the uuid inside the `_nobleConnect` function

Can you elaborate on this comment above? What did you change them to? How many of them did you change? Show me a snippit of the code you modified. 

I do not have the means to reprogram the RFDuino/Cyton I have on hand and won't till the end of the week to duplicate these problems, I apologize, I had to travel to another location this week out of the range of the OpenBCI lab.

**Comment by itisnas** [comment]
I see,

So I haven't modified any code in Arduino. All I did, is added an if statement inside the OpenBCICytonBLE.js:

```js
CytonBLE.prototype._nobleConnect = function (peripheral) {
  return new Promise((resolve, reject) => {
    if (this.isConnected()) return reject('already connected!');

    this._peripheral = peripheral;
    this._localName = peripheral.advertisement.localName;
    if (this.options.verbose) console.log('Device is advertising \'' + this._peripheral.advertisement.localName + '\' service.');
    // TODO: filter based on advertising name ie make sure we are looking for the right thing
    //if (this.options.verbose) console.log("serviceUUID: " + this._peripheral.advertisement.serviceUuids);
    
      this._peripheral.on(k.OBCINobleEmitterPeripheralConnect, () => {
      // if (this.options.verbose) console.log("got connect event");
      this._peripheral.discoverServices();
      if (this.isSearching()) this._nobleScanStop();
    });

    this._peripheral.on(k.OBCINobleEmitterPeripheralDisconnect, () => {
      if (this.options.verbose) console.log('Peripheral disconnected');
      this._disconnected();
    });

    this._peripheral.on(k.OBCINobleEmitterPeripheralServicesDiscover, (services) => {
      //console.log("insider 1: ", services, " checking: ", k.RFduinoUuidService);
      for (let i = 0; i < services.length; i++) {
        console.log("services[i].uuid: ", services[i].uuid, k.RFduinoUuidService);

        // ======= Added my if{...} statement ======== \\
        let testing = "";
        if (services[i].uuid === '0000180000001000800000805f9b34fb') {
          services[i].uuid = "1800";
          testing = "1800"
        } else if(services[i].uuid === "0000180100001000800000805f9b34fb") {
          services[i].uuid = "1801";
          testing = "1801"
        } else {
          services[i].uuid = "2220";
          testing = "2220"
        }

        // ========= end of my addition ===========

         // important!: since the UUID is different, this will never be true unless I do the if statement above
        // This means if we can make our arduino return the right uuid, the below if statement will be true
        if (services[i].uuid === k.RFduinoUuidService) { 
          this._rfduinoService = services[i];
          // if (this.options.verbose) console.log("Found rfduino Service");
          break;
        }
      }
      if (!this._rfduinoService) {
        reject('Couldn\'t find the rfduino service.');
      }
      ...
``` 

That if statement all it does is check the UUID that I receive, and basically change it to what is in the conctant.js. This way I can bypass the error of getting null for `this._rfduinoService`. Now the whole problem is in me receieving the UUID which is different than what you'd expect (`2220`).

@aj-ptw

**Comment by itisnas** [comment]
Hi there,

I'm trying to follow your undo step in the readme, and now its throwing this error. I've been stuck in this for 3 hours, any ideas?

<img width="783" alt="capture" src="https://user-images.githubusercontent.com/16179773/35631195-2be44e5c-069b-11e8-841b-83f0f812d1a0.PNG">
@aj-ptw 


I've tried following this step...Doesnt work:
<img width="691" alt="capture" src="https://user-images.githubusercontent.com/16179773/35631408-b9f6210c-069b-11e8-90e2-5c9df2beb745.PNG">

**Comment by andrewjaykeller** [comment]
You don’t have the correct firmware on possibly both RFDuinos, you need the host code on dongle and device code on Cyton RFDuino in order to do over the air uploading.

**Comment by itisnas** [comment]
@aj-ptw Is there tutorial on how to do this?

**Comment by itisnas** [comment]
@aj-ptw  Ok so this is what I did for the dongle:
<img width="977" alt="capture" src="https://user-images.githubusercontent.com/16179773/35634497-bd969ed8-06a3-11e8-9da8-6b565e45fb42.PNG">

And this is what I did for the board:
<img width="916" alt="capture" src="https://user-images.githubusercontent.com/16179773/35634549-dc03e5e2-06a3-11e8-9bdb-02a5ded2fdf0.PNG">

I don't see what the problem is now?

**Comment by itisnas** [comment]
Is there a way to reset everything and go back to factory state? If not, then I'd appreciate your help to fix this. I have no idea what to do, now BLE doesn't work, nor the board. I cant upload now. @aj-ptw

**Comment by andrewjaykeller** [comment]
@NaseebullahSafi sorry you're having these troubles, I' assure you there is _always_ a way to get the board back to it's default state.

Can you please use the GUI to see if your radio system is up? [Tutorial here](http://docs.openbci.com/Tutorials/01-Cyton_Getting%20Started_Guide#cyton-getting-started-guide-iv-connect-to-your-cyton-board-from-the-gui-6-optional-settings)

You may try pressing the auto scan button as well to realign your radio channels. The Host and Device must be on the same channel, perhaps that's why you're getting the "No Target Found" error message.

You are following the tutorial for [uploading radios code](http://docs.openbci.com/Hardware/06-Cyton_Radios_Programming_Tutorial)

**Comment by itisnas** [comment]
It's ok, I'm learning at the same time. And I'm sorry for putting you through all this. 

So I pressed the auto scan, and it says "Failure: system is down" @aj-ptw

**Comment by andrewjaykeller** [comment]
Sounds like you did not upload the one of the RFDuino's firmware's correctly.

Did you upload RadioDevice32bit.ino code to the Device RFDuino on the Cyton?

Is the blue light on the dongle? Is the dongle running RadioHost32bit.ino code? Is the switch in GPIO6 position when you are hitting autoscan?

**Comment by itisnas** [comment]
> Did you upload RadioDevice32bit.ino code to the Device RFDuino on the Cyton?

Yes, I have done this.

> Is the blue light on the dongle?

Yes

>  Is the dongle running RadioHost32bit.ino code?

Yes

> Is the switch in GPIO6 position when you are hitting autoscan?

Yes

@aj-ptw

**Comment by itisnas** [comment]
And the last step of your undo section in the READme is where I'm stuck.

> Upload DefaultBoard.ino to the Cyton's Pic32 over the air following this tutorial

I cant do this part

**Comment by andrewjaykeller** [comment]
You cannot do the last step in the tutorial until your radios are communicating together. The radio utility in the GUI **must** say Success: System is up in order for you to ever program the Cyton's Pic 32 microcontroller over the air

**Comment by andrewjaykeller** [comment]
Do you get success messages when you upload the code to the RFDuino's?

**Comment by itisnas** [comment]
@aj-ptw yes for both 2 steps:

Prints:

=======

Success!

=======

**Comment by itisnas** [comment]
> Did you upload RadioDevice32bit.ino code to the Device RFDuino on the Cyton?

For this, note that the switch in the dongle was on RESET, as suggested in tutorial
@aj-ptw

**Comment by andrewjaykeller** [comment]
I was typing a long instruction set but yea that's wrong if you kept the switch in the reset position. Upload the pass through code with switch in reset on dongle. flip switch to gpio6, upload radiodevice32bit to Device (cyton rfduino), flip switch on dongle to reset, upload RadioHost32bit to dongle, flip switch back to gpio6, done.

**Comment by itisnas** [comment]
ok now that make sense. Im doing that again.

**Comment by andrewjaykeller** [comment]
This is probably why your BLE adverstiment packets were all wrong, maybe not though, but I would make sure you uploaded the BLE code just incase this was the problem.

**Comment by itisnas** [comment]
I really hope that is the case.

**Comment by andrewjaykeller** [comment]
False hope is what keeps me going ;)

**Comment by itisnas** [comment]
Ok,

Success!
=

for 
> I was typing a long instruction set but yea that's wrong if you kept the switch in the reset position. Upload the pass through code with switch in reset on dongle. flip switch to gpio6, upload radiodevice32bit to Device (cyton rfduino), flip switch on dongle to reset, upload RadioHost32bit to dongle, done.

I'm gonna now follow your last step. See if it works. BTW for step 3, it should switch to gpi06 right?

**Comment by NaseebullahSafi** [comment]
Ok, Ive followed your last step aswell. The switch in the dongle was towards GPIO6. The switch in the board was in PC.
<img width="1062" alt="capture" src="https://user-images.githubusercontent.com/16179773/35641582-80312c6a-06b8-11e8-96d4-3e9182d996fe.PNG">

And I still get the same error.

Btw the last step was not over hardwire, but over the air

**Comment by NaseebullahSafi** [comment]
And the GUI is saying:

<img width="517" alt="capture" src="https://user-images.githubusercontent.com/16179773/35641719-ddebbfa0-06b8-11e8-8a9c-69a7baffa972.PNG">

**Comment by itisnas** [comment]
Oh my god! I think I'm in heaven:
<img width="1509" alt="capture" src="https://user-images.githubusercontent.com/16179773/35642144-1948b1c4-06ba-11e8-8b75-797b35b1463c.PNG">

Wow, so so far so good. I'm gonna now do the whole step for the BLE, and hope for success. @aj-ptw

**Comment by itisnas** [comment]
@aj-ptw Ok So I did BLE enabling and the UUID's are still the same.I'm just gonna explain every step I took and you can tell me where I went wrong:

>
1. Upload BoardWithBLE.ino to the Cyton's Pic32 over the air following this tutorial
    => Plugged Dongle => switch to GPIO6
    => Initiate Bootmode for the board  => switch of Board at PC
    => Arduino 1.8.5 => examples => OpenBCI_32bit_Library => BoardWithBLE => Initiate upload

>
2. Upload DefaultRadio.ino to the Cyton's RFDuino through hardwire following this tutorial where you use the DefaultRadio.ino from OpenBCI_RFDuino_BLE. If you don't have an FTDI programmer and need to use the Dongle that shipped with your Cyton, then be sure to follow the part in the tutorial about uploading the pass through code to the Dongle.
    => [`git cloned`](https://github.com/PushTheWorld/OpenBCI_RFDuino_BLE) into [`C:\Users\Nasee\Documents\Arduino\libraries`]()
    => Opened ***`Arduino 1.5.8 Beta`*** => examples => OpenBCI_Radios -> RadioPassThru32bit
    => Plugged Dongle => switch to Reset => Initiate upload 
    => Switch to GPIO6 => OpenBCI_RFDuino_BLE -> DefaultRadio => Initiate upload
    => Switch to Reset => OpenBCI_Radios -> RadioHost32Bit => Initiate Upload


This successfully enabled BLE, and I could see it in my phone.
I ran my app, and I still get the same UUIDs

<img width="1056" alt="capture" src="https://user-images.githubusercontent.com/16179773/35645098-c0bc8504-06c2-11e8-9960-485d8cdab176.PNG">


I tried using a react native module to test the BLE, and here's what they returned:
<img width="1051" alt="capture" src="https://user-images.githubusercontent.com/16179773/35645665-7575f39e-06c4-11e8-9c17-5217884d869c.PNG">

I think my board is returning the correct service in this react module, but not long uuid in your module.
I can't use their module because its only use for connectivity, whatI'd prefer is to use your approach and your module

**Comment by andrewjaykeller** [comment]
What operating system are you using? What version of node?

**Comment by andrewjaykeller** [comment]
Great write up btw, I’m on my way towards NYC and will test.

**Comment by itisnas** [comment]
I'm using 
Windows 10
node version 8.9.4
npm version 5.6.0

@aj-ptw

**Comment by itisnas** [comment]
Thank you AJ really appreciate your help. Just a heads up that you guys are doing a great job, I'm doing my final year project on OpenBCI + I've been asked to show a final app using Cyton to a big company. I shall hope we spread the word about this great product

**Comment by andrewjaykeller** [comment]
Awesome I will duplicate with a little more help

What terminal program are you using to run the example program? power shell, cmd prompt, etc...
What type of bluetooth low energy adapter do you have?

> Thank you AJ really appreciate your help. Just a heads up that you guys are doing a great job, I'm doing my final year project on OpenBCI + I've been asked to show a final app using Cyton to a big company. I shall hope we spread the word about this great product

No problem, customer service is [our number one value](https://www.pushtheworldllc.com/), learning how people want to interface with this and supporting them is in our core!

**Comment by itisnas** [comment]
I'm using a terminal that comes with IntelliJ IDE. 

I'm not sure what you mean by Bluetooth low energy adapter. I'm using Samsung s8 charger cable to connect to my laptop to run my app.

Currently Cyton dongle is connected to my PC, and I enable BLE from my Samsung s8

@aj-ptw

**Comment by andrewjaykeller** [comment]
You computer has ble built in?

**Comment by andrewjaykeller** [comment]
I always used the CSR dongle on windows with that node app...

**Comment by itisnas** [comment]
Honestly I don't know, but seeing that the BLE works without me using an adapter, then I think it has. Let me confirm.

**Comment by itisnas** [comment]
<img width="271" alt="capture" src="https://user-images.githubusercontent.com/16179773/35648715-89f5fbd4-06ce-11e8-9a69-92fd6b3b15fe.PNG">

Yeh it has @aj-ptw

**Comment by andrewjaykeller** [comment]
Hey did you use the zadig tool to update your windows drivers? This tutorial is for the ganglion, but it should be followed for you as well. You may try to using the Zadig tool to replace the driver for your Bluetooth comm port. This driver uses `noble` which has it's own requirements for supporting windows.

**Comment by itisnas** [comment]
I haven't actually. Let me try @aj-ptw

**Comment by andrewjaykeller** [comment]
That could be an issue, I just tried uploading the Default radio to a cyton and got good UUID's:

![img_0546](https://user-images.githubusercontent.com/11437469/35681401-484ac46e-072b-11e8-8dde-5328933b14d5.jpg)

**Comment by itisnas** [comment]
Can you try running the same thing on Android, I have a feeling theres a difference from IOS @aj-ptw

**Comment by andrewjaykeller** [comment]
Here I am using this node driver to connect to the device:

![screen shot 2018-02-01 at 8 41 49 am](https://user-images.githubusercontent.com/11437469/35681579-cc342586-072b-11e8-8d63-cf936f7cdf91.png)

**Comment by andrewjaykeller** [comment]
I do not have an Android device on hand.

**Comment by itisnas** [comment]
Ah right, I see. Ok literally just downloaded Zadig and installed WCID driver.

**Comment by andrewjaykeller** [comment]
i think it's winUSB that you want. Also you might as well update this module to 0.1.2 that was just released for a bug fix

**Comment by andrewjaykeller** [comment]
Make sure you meet these:

https://github.com/sandeepmistry/noble#windows

**Comment by itisnas** [comment]
So I updated the Zadic to winusb, and still gives me that long uuid. I'm gonna now update the noble module to see if it works

<img width="1063" alt="capture" src="https://user-images.githubusercontent.com/16179773/35682118-79245b5a-0757-11e8-8402-5e5643e42b45.PNG">

**Comment by itisnas** [comment]
Ah ok sorry, I had forgotten some extra step. Have a feeling this might work. Hang in there

**Comment by itisnas** [comment]
Just wanted to make sure, in the list I get this:
<img width="433" alt="capture" src="https://user-images.githubusercontent.com/16179773/35683180-1125943e-075b-11e8-8dc8-7c9ee0387888.PNG">
and "SAMSUNG_Android". Do I update both? @aj-ptw

**Comment by andrewjaykeller** [comment]
Not sure what `SAMSUNG_Android` is so don't change it.

**Comment by itisnas** [comment]
So I've been busy trying to make this work, and just have no idea:
<img width="928" alt="capture" src="https://user-images.githubusercontent.com/16179773/35703779-3ae3cc70-0795-11e8-9c37-38554f2fe2cc.PNG">

And this is when I'm searching for peripheral:
<img width="924" alt="capture" src="https://user-images.githubusercontent.com/16179773/35705709-23c95dc4-079b-11e8-9d46-b62ac9f47757.PNG">


So I followed the windows requirement and whatnot, and that's what i get from the above.

Then I try to run it in my app, and I get:
<img width="1063" alt="capture" src="https://user-images.githubusercontent.com/16179773/35703851-72abfd3a-0795-11e8-9290-0a1ec93a8ad0.PNG">

@aj-ptw

**Comment by itisnas** [comment]
And even after the steps above, I still get this:
![capture](https://user-images.githubusercontent.com/16179773/35704881-c1025544-0798-11e8-9793-7d9d39cc6ddd.PNG)

**Comment by itisnas** [comment]
I found the issue @aj-ptw In android it's giving out the long format of the UUID. whereas in my iPhone, it's giving me the short one (i.e. 2220). I don't know how to fix this.

**Comment by andrewjaykeller** [comment]
Is there a setting we can change to get the short UUIDs in android? I wonder where those other numbers are coming from!

**Comment by itisnas** [comment]
In BLE GATT, that's the layout. I just need to know how to get the shorter version. Everything else works superbly. It's just the connecting part.

**Comment by itisnas** [comment]
I'm posting this question in SO to see what people say about BLE

**Comment by andrewjaykeller** [comment]
Hmm... So i know there is a short and a long version, but i though this was determined by the server, the RFDuino here, and read by the client, the android.

**Comment by itisnas** [comment]
So here's the thing. The issue is not in our project, (nor yours nor mines) Before we even run it in our app, we're getting two different results when we use ble scanner from iPhone and Android. So the issue lies in the different platform. Is there a way to add also include the longer version in your project? Or will that be too much? @aj-ptw

**Comment by itisnas** [comment]
As in, the constant.js says to look for a match 2220, can we also add the longer version aswell?

**Comment by andrewjaykeller** [comment]
This project piggy backs on RFDuino, no characters are set by the end user. If we can figured out how to change the RFDuino UUID in firmware then this can be easy, last I checked there was not a way but perhaps I’m wrong.

**Comment by andrewjaykeller** [comment]
Oh yes totally re adding the longer ids

**Comment by andrewjaykeller** [comment]
I thought you said swapping the uuid with the longer didn’t work in the node js

**Comment by itisnas** [comment]
I see. I'm thinking if we do this, then not only is your RFDuino is suitable for one platform but cross-platform, this includes IOS and android apps. It would be too good tbh.

**Comment by itisnas** [comment]
@aj-ptw That was done as soon as I got the GATT service. So changing it might cause secruity alert. i.e. from noble.

**Comment by itisnas** [comment]
What if in the constant we have the longer version, and then in the OpenBCI js file, we add disjunction condition (`||`) to see which ever matches?

**Comment by itisnas** [comment]
The reason why It didn't work for me was that I had explicitly changed the props of the object within the eventEmitters in your OpenBCI.js file. We need to have an eventEmitter beforehand looking for both versions.

**Comment by andrewjaykeller** [comment]
please try version `0.1.3` where I added your long UUIDs and put or statements in

**Comment by itisnas** [comment]
Also please change this:
<img width="485" alt="capture" src="https://user-images.githubusercontent.com/16179773/35732235-9d4fd252-0810-11e8-95cc-a0cc481764ee.PNG">
@aj-ptw

**Comment by andrewjaykeller** [comment]
Please prove that these long UUIDs create a system that works and then we can add these to the constants.js file in the utilities module.

This driver, as of 0.1.3, _should_ work for you.

**Comment by itisnas** [comment]
Ok good news, at leats we're getting different error now.
<img width="1009" alt="capture" src="https://user-images.githubusercontent.com/16179773/35732835-e526153a-0812-11e8-9bbb-81114434c3c9.PNG">

**Comment by itisnas** [comment]
the charachteristic seems to be empty:
<img width="1015" alt="capture" src="https://user-images.githubusercontent.com/16179773/35732870-0a055898-0813-11e8-8f46-44bceda3592d.PNG">

**Comment by itisnas** [comment]
Ok so it's not an error at all. Everything works now. But the thing is, I'm not quite sure, is the characteristic array the actual value that comes from the Arduino? Currently its empty hence the error. @aj-ptw

**Comment by andrewjaykeller** [comment]
Ugh... whyyyy

What is `this._rfduinoService` being set to? That needs to be set to the service ID in order to discover the characteristics about that service.

**Comment by itisnas** [comment]
It is set to the following, which is correct:

<img width="1012" alt="capture" src="https://user-images.githubusercontent.com/16179773/35735681-82cdb46e-081d-11e8-98b9-e01ee76df929.PNG">

@aj-ptw

**Comment by itisnas** [comment]
but the characteristics seem to be empty

**Comment by andrewjaykeller** [comment]
Can you try over riding the uuid with the 2220? Maybe use the long uuid to find it but actually set the receive characteristic to the 2220?

**Comment by itisnas** [comment]
The thing is, even if I do that, the object that returns it, the characteristics is empty. But sure I'll try as I have no clue

**Comment by itisnas** [comment]
Apologies. I had to take a break from trying to integrate this into my project and go ahead with other plans so as to not get behind. Unfortunately, there's no way of integrating this to a mobile app. Please refer to the new issue (which I'll create right now) to explain why.
